node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     dir("basics"){
      docker.withRegistry('https://index.docker.io/v1/', 'lidor-dockerhub') {
        def app = docker.build("naturalett/playground:${commit_id}", '.').push()
      }
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test || true
      docker run --rm -tid --name docker_test -p 3000 naturalett/playground:latest
      docker kill docker_test
      
      '''
     }
    stage("Set description") {
      currentBuild.displayName = "My custom build name"
      currentBuild.description = "My custom build description"
    }
   }

