name: CI

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest twine

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
        python -m pytest python/program-calc/calculate/unit_tests.py --junit-xml test-results/unit_test_results.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Python Package
      run: |
        python setup.py sdist bdist_wheel
        pip install pytest

  artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Artifact in PyPi
      run: |
        twine upload dist/*

