name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Run unittests
      run: python -m unittest program-calc/calculate/unit_tests.py

  deployment:

    runs-on: ubuntu-latest

    environment: 
      name: production
      url: https://github.com

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Deployment!
