name: CI

on: [push]

env:
  ARTIFACT_FOLDER: path/to/artifacts

jobs:
  initiate:
    name: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

  test:
    name: test
    needs: initiate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest python/program-calc/calculate/unit_tests.py --junit-xml test-results/unit_test_results.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build artifact
      run: |
        mkdir -p path/to/artifacts
        cd python/program-calc    
        python setup.py sdist bdist_wheel
    - name: Copy artifact
      run: |
        ls -al path/to/artifacts
        cp -R dist/* path/to/artifacts
        ls -al path/to/artifacts
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifacts

  artifact:
    name: artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve saved artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifacts
    - name: Upload artifact
      run: |
        pip install twine
        cd path/to/artifacts
        twine upload *

