name: CI

on: [push]

env:
  ARTIFACT_FOLDER: python/program-calc/sdist

jobs:
  initiate:
    name: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

  test:
    name: test
    needs: initiate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest python/program-calc/calculate/unit_tests.py --junit-xml test-results/unit_test_results.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build artifact
      run: |
        cd python/program-calc
        python setup.py sdist bdist_wheel
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: $ARTIFACT_FOLDER
    - run: ls -al $ARTIFACT_FOLDER/

  artifact:
    name: artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: $ARTIFACT_FOLDER
    - run: |
        pip install twine
        cd python/program-calc
        twine upload dist/*

