name: CI

on: [push]

env:
  ARTIFACT_FOLDER: path/to/artifacts

jobs:
  initiate:
    name: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

  test:
    name: test
    needs: initiate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest python/program-calc/calculate/unit_tests.py --junit-xml test-results/unit_test_results.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set env
      run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
    - name: Build artifact
      run: |
        cd python/program-calc
        ls -al
        ls -al calculate
        python setup.py sdist bdist_wheel
        ls -al
        mkdir -p ${{ env.workspace }}/dist
        ls -al dist
        ls -al ${{ env.workspace }}
        pwd
    - name: Copy artifact
      run: |
        pwd
        cd python/program-calc
        cp -r dist/* ${{ env.workspace }}/dist/
        ls -al ${{ env.workspace }}/dist/
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ env.workspace }}

  artifact:
    name: artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print dir content
      run: |
        pwd
        ls -al
        ls -al python/program-calc/
    - name: Retrieve saved artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ${{ env.workspace }}
    - run: ls -al ${{ env.workspace }}/dist/
    - name: Upload artifact
      run: |
        pip install twine
        cd /tmp
        twine upload *

