name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest calculate/unit_tests.py

  deployment:

    runs-on: ubuntu-latest

    environment: 
      name: production
      url: https://github.com

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Deployment!
